### ISSUE TITLE
bugfix/todo list

### ISSUE THREAD

**Issue by 4techguns** [4techguns/4techguns.github.io#1]
### Bugs
- [x] 1 Fix logo not being displayed
    - [x] 1.1 fix logo positioning

- [x] 2 Fix dirt background not showing

- [x] 3 Fix a thing I screwed up doing while trying to link to 4techguns.tk
    - [x] 3.1 Remove the ad redirection by messing with the domain thingy and some patience
    - [x] 3.2 Try to remove the 4techguns.tk domain and its redirection completely

### Todo
- [x] ~~4 Make 3 more pages so the page buttons actually have a use~~ removed for now
